/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lacreacion.remates;

import java.awt.Color;
import javax.swing.DesktopManager;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class MdiFrame extends javax.swing.JFrame {

    JDesktopPane desktop;
    DesktopManager manager;
    private String databaseIP;

    /**
     * Creates new form MDIFrame
     */
    public MdiFrame() {
        initComponents();
        desktop = new JDesktopPane();
        desktop.setBackground(Color.white);
        setContentPane(desktop);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuMiembros = new javax.swing.JMenuItem();
        mnuMiembros3 = new javax.swing.JMenuItem();
        mnuMiembros4 = new javax.swing.JMenuItem();
        mnuCategorias = new javax.swing.JMenuItem();
        mnuMiembros1 = new javax.swing.JMenuItem();
        mnuMiembros2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Operaciones");

        jMenuItem2.setText("Remates");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Pagos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Configuracion");

        mnuMiembros.setText("Administrar Miembros");
        mnuMiembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMiembrosActionPerformed(evt);
            }
        });
        jMenu2.add(mnuMiembros);

        mnuMiembros3.setText("Administrar Remates");
        mnuMiembros3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMiembros3ActionPerformed(evt);
            }
        });
        jMenu2.add(mnuMiembros3);

        mnuMiembros4.setText("Administrar Cuotas de Remates");
        mnuMiembros4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMiembros4ActionPerformed(evt);
            }
        });
        jMenu2.add(mnuMiembros4);

        mnuCategorias.setText("Administrar Categorias de Articulos");
        mnuCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCategoriasActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCategorias);

        mnuMiembros1.setText("Administrar Transferencias");
        mnuMiembros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMiembros1ActionPerformed(evt);
            }
        });
        jMenu2.add(mnuMiembros1);

        mnuMiembros2.setText("Administrar Recibos");
        mnuMiembros2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMiembros2ActionPerformed(evt);
            }
        });
        jMenu2.add(mnuMiembros2);

        jMenuItem5.setText("Configuracion del Sistema");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 934, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuMiembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMiembrosActionPerformed
        try {
            FrameMiembros frame = new FrameMiembros();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
        }
    }//GEN-LAST:event_mnuMiembrosActionPerformed

    private void mnuCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCategoriasActionPerformed
        try {
            FrameRematesCategorias frame = new FrameRematesCategorias();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
            ex.printStackTrace();
        }

    }//GEN-LAST:event_mnuCategoriasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            FrameRematesDetalle frameR = new FrameRematesDetalle();
            frameR.setVisible(true);

            desktop.add(frameR);

            frameR.setSelected(true);
            frameR.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            FramePagos frame = new FramePagos();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            FrameConfig frame = new FrameConfig();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void mnuMiembros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMiembros1ActionPerformed
        try {
            FrameTransferencias frame = new FrameTransferencias();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_mnuMiembros1ActionPerformed

    private void mnuMiembros2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMiembros2ActionPerformed
        try {
            FrameRecibos frame = new FrameRecibos();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_mnuMiembros2ActionPerformed

    private void mnuMiembros3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMiembros3ActionPerformed
        try {
            FrameRematesAdmin frame = new FrameRematesAdmin();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_mnuMiembros3ActionPerformed

    private void mnuMiembros4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMiembros4ActionPerformed
        try {
            FrameCuotasAdmin frame = new FrameCuotasAdmin();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_mnuMiembros4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
             System.out.println(info.getName());
             if ("Nimbus".equals(info.getName())) {
             javax.swing.UIManager.setLookAndFeel(info.getClassName());
             break;
             }*/
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MdiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MdiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MdiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MdiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MdiFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem mnuCategorias;
    private javax.swing.JMenuItem mnuMiembros;
    private javax.swing.JMenuItem mnuMiembros1;
    private javax.swing.JMenuItem mnuMiembros2;
    private javax.swing.JMenuItem mnuMiembros3;
    private javax.swing.JMenuItem mnuMiembros4;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the databaseIP
     */
    public String getDatabaseIP() {
        return databaseIP;
    }

    /**
     * @param databaseIP the databaseIP to set
     */
    public void setDatabaseIP(String databaseIP) {
        this.databaseIP = databaseIP;
    }
}
